#!/bin/bash
tee /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF
sleep 5
modprobe overlay
modprobe br_netfilter
tee /etc/sysctl.d/kubernetes.conf<<EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF
sleep 5
sysctl --system
sleep 5
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sleep 5
apt update
sleep 5
apt install -y containerd.io
sleep 5
mkdir -p /etc/containerd
sleep 20
containerd config default>/etc/containerd/config.toml
sed -e 's/SystemdCgroup = false/SystemdCgroup = true/g' -i /etc/containerd/config.toml
systemctl daemon-reload
systemctl restart containerd
systemctl enable containerd
apt-get update && apt-get install -y apt-transport-https ca-certificates curl
sleep 5
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
KUBE_VERSION=1.23.0
apt-get update
sleep 10
apt-get install -y kubelet=${KUBE_VERSION}-00 kubeadm=${KUBE_VERSION}-00 kubectl=${KUBE_VERSION}-00 kubernetes-cni=0.8.7-00
sleep 5
apt-mark hold kubelet kubeadm kubectl 
systemctl enable kubelet && systemctl start kubelet
apt-get install firewalld
apt install selinux-utils
kubeadm init --kubernetes-version=${KUBE_VERSION}
#sudo sed -i '/swap/d' /etc/fstab
#sudo swapoff -a
#sleep 5
#sudo firewall-cmd --permanent --add-port=6443/tcp
#sudo firewall-cmd --permanent --add-port=2379-2380/tcp
#sudo firewall-cmd --permanent --add-port=10250/tcp
#sudo firewall-cmd --permanent --add-port=10251/tcp
#sudo firewall-cmd --permanent --add-port=10252/tcp
#sudo firewall-cmd --permanent --add-port=10255/tcp
#firewall-cmd --reload
#sudo setenforce 0
#sudo sed -i ‘s/^SELINUX=enforcing$/SELINUX=permissive/’ /etc/selinux/config
